import com.android.build.api.artifact.SingleArtifact
import com.android.build.api.variant.AndroidComponentsExtension

plugins {
    id "com.android.application"
    id "dev.rikka.tools.refine"
}

android {
    namespace = "rikka.shizuku.shell"
    defaultConfig {
        versionCode = rootProject.ext.versionCode
        versionName = rootProject.ext.versionName
        buildConfigField "String", "MANAGER_APPLICATION_ID", "\"${project(':manager').android.defaultConfig.applicationId}\""
    }
    buildTypes {
        debug {
            multiDexEnabled = false
        }
        release {
            minifyEnabled = true
            proguardFiles = ["proguard-rules.pro"]
        }
    }
    dependenciesInfo {
        includeInApk = false
    }
    lint {
        checkReleaseBuilds = false
    }
    buildFeatures {
        buildConfig = true
    }
}

def androidComponents = project.extensions.getByType(AndroidComponentsExtension)

androidComponents.onVariants(androidComponents.selector().all()) { variant ->
    variant.outputs.each { output ->
        output.outputFileName.set("shizuku-v${rootProject.ext.versionName}-${variant.name}.apk")
    }

    def isMinified = android.buildTypes.getByName(variant.buildType).minifyEnabled
    def assembleTaskName = "assemble${variant.name.capitalize()}"

    tasks.matching { it.name == assembleTaskName }.configureEach { t ->
        t.doLast {
            def outDir = new File(rootDir, "out")
            def mappingDir = new File(outDir, "mapping")
            def apkDir = new File(outDir, "apk")

            if (isMinified) {
                def mappingFile = variant.artifacts
                        .get(SingleArtifact.OBFUSCATION_MAPPING_FILE)
                        .get().asFile
                copy {
                    from mappingFile
                    into mappingDir
                    rename { "mapping-${rootProject.ext.versionName}.txt" }
                }

                def apkFolder = variant.artifacts
                        .get(SingleArtifact.APK)
                        .get().asFile
                copy {
                    from apkFolder
                    into apkDir
                    include "*.apk"
                }
            }
        }
    }
}

dependencies {
    implementation libs.hidden.compat
    compileOnly libs.hidden.stub
}
