plugins {
    id "com.android.library"
    id "dev.rikka.tools.refine"
}

android {
    namespace = "moe.shizuku.server"
    buildFeatures {
        buildConfig = true
    }
    defaultConfig {
        buildConfigField "String", "MANAGER_APPLICATION_ID", "\"${project(':manager').android.defaultConfig.applicationId}\""
    }
}

dependencies {
    implementation libs.androidx.annotation
    implementation libs.gson
    api libs.rikkax.parcelablelist

    implementation project(":aidl")
    implementation project(":common")
    implementation project(":shared")
    compileOnly project(":provider")
    implementation project(":starter")
    implementation project(":rish")
    implementation project(":server-shared")
    implementation libs.hidden.compat
    compileOnly libs.hidden.stub
}
